// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxafjmrdjmrmzucpifot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4YWZqbXJkam1ybXp1Y3BpZm90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Njk3MDIsImV4cCI6MjA3MTI0NTcwMn0.H_bRG9Vske-XNGLz4tLvzjGm_wApYy_7Kh4Hmj7Y7xE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});